### ISSUE TITLE
Analog Input Mode * Low signal / Gain issue

### ISSUE THREAD

**Issue by TWonday** [yurikleb/DRV2667#1]
Hi, first of all thank you very much for the library, Saved me a lot of work.
Just wanted to add that I was having problems with the AnalogInput mode.

When I power up the arduino and the DRV2605, the arduino programs the DRV according to your demo, then the feedback is really low and I think its due to the gain.
If i now restart only the arduino, e.g. through opening serial monitor, but everything and especially hte DRV stay powered on, then the arudino re-programs the DRV and the gain must be higher since the feedback is significantly higher.

I think I fixed this by changing the following lines : 

`void Yurikleb_DRV2667::setToAnalogInput(){
  Serial.println("Switching to Analog Input Mode");
  //control
  writeRegisterBytes(0x02, 0x00); //Take device out of standby mode
  writeRegisterBytes(0x01, 0x07); //Set to analog input 0x04 + Gain 0x00-0x03 		
  writeRegisterBytes(0x02, 0x02); //Set EN_OVERRIDE bit = boost and amplifier active
}`

So I simply changed the order to first set amplifier active and then set the gain :  

`void Yurikleb_DRV2667::setToAnalogInput(){
  Serial.println("Switching to Analog Input Mode");
  //control
  writeRegisterBytes(0x02, 0x00); //Take device out of standby mode
  writeRegisterBytes(0x02, 0x02); //Set EN_OVERRIDE bit = boost and amplifier active
  writeRegisterBytes(0x01, 0x07); //Set to analog input 0x04 + Gain 0x00-0x03 		
}`

For me this fixes it so that the gain is also high on start-up. 
As I said I'm only running the demo code so the only lines are : 

`drv.begin();  
    drv.setToAnalogInput();  //Swithch To Analog
 `

Hope this helps /  if I'm wrong somewhere I'm welcome for corrections .
 Tommy

**Comment by yurikleb** [comment]
Hey Tommy, thanks for the feedback!
Please note that this library is supposed to be used with the DRV2667 which is a Piezo actuators driver.
The DRV2605 is a completely different driver.
So the commands it takes and their order might be very different from the DRV2667.

So I'm not sure my library is recommended to use with the DRV2605.
Adafruit have great libraries and support for the DRV2605: https://learn.adafruit.com/adafruit-drv2605-haptic-controller-breakout/overview

**Comment by TWonday** [comment]
Hi Yuri,
Yeah sorry, correction, I meant the DRV2667, I've been using both so mixed it up. 
Im using the [Tindie module ](https://www.tindie.com/products/Fyberlabs/piezo-haptic-flex-module/)

**Comment by yurikleb** [comment]
Sorry for the super late response.
Just updated the code based on your recommendation.

Thanks for pointing that out!
