### ISSUE TITLE
Actuator choice

### ISSUE THREAD

**Issue by james-bird** [yurikleb/DRV2667#3]
Hello,

Which actuator did you use with this driver? How strong was the feedback?

Many thanks,

James

**Comment by yurikleb** [comment]
Hey James,
I was using this in a haptic feedback device, and the actuators were touching the user skin:
http://www.yurikleb.com/portfolio/vito/
So just [simple piezo transducers](https://www.amazon.com/TIMESETL-Pickup-Amplifiers-Acoustic-Guitar/dp/B077YJ3H6R/ref=sr_1_1_sspa?ie=UTF8&qid=1532059467&sr=8-1-spons&keywords=piezo&psc=1) were enough.
They come in many different sizes and are very cheap so the best thing is just to get a bunch and tet what works best for you.

If you need something stronger you can try the [Samsung actuators](https://www.tindie.com/products/Fyberlabs/samsung-piezo-actuator-x5/) which you can get from the same guy on Tindie that sells the breakout boards. Those are actually similar to what TI provide on their [EVM Board](http://www.ti.com/tool/drv2667evm-ct) which they sell to demonstrate the capabilities of the chip.

Hope this helps.

**Comment by yurikleb** [comment]
[simple piezo transducers](url)

**Comment by james-bird** [comment]
Hi Yuri,

That is very helpful, thank you very much.

James

**Comment by VijayPediredla** [comment]
Hi,
Regd. the code for  Arduino DRV 2667 Haptic Piezo Driver Control in Instructables
1) In the example code, it is said that by changing the amplitude (A), frequency (F), duration (D) and envelope (E), we can change the displacement of vibration in the actuator. Can you give me the formulation of the above; I mean, mapping of the  50V-100V,  0-255 to the original values of amplitude (mm), frequency (Hz), and significance of duration and envelope in actuation?
2) In the examples (basic_analog), what is the input to actuate the actuator? Can you briefly elaborate?

**Comment by yurikleb** [comment]
Hey @Vijay3059 ,

1. 

1.  adsas

**Comment by yurikleb** [comment]
Hey @Vijay3059 

Please see the DRV2667 Datasheet page 19: http://www.ti.com/lit/ds/symlink/drv2667.pdf which explains how the driver handles the amplitude, frequency, duration and envelope values.
The actual physical output (movement in mm etc..) can change depending on the type of the actuators you use.

For analogue input, you can use any device that can output an analogue waveform, the most simple would be any audio player, you can just solder an audio jack to the driver analogue input as I did in the Instructables tutorial, then plug it to your media player/phone with an AUX cable.
If you want to generate accurate analogue waveforms you can use an oscilloscope for example https://learn.sparkfun.com/tutorials/how-to-use-an-oscilloscope/all
